import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavBar } from "./_components/layout/navbar";
import { Footer } from "./_components/layout/footer";
import { getCountries } from "@/services/countries.service";
import { CountriesProvider } from "@/context/countries.context";
import { ReactQueryProvider } from "@/context/react-query.context";
import { NuqsAdapter } from "nuqs/adapters/next/app";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const countries = await getCountries();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen overflow-x-hidden scroll-auto bg-white antialiased flex flex-col`}
      >
        <NuqsAdapter>
          <ReactQueryProvider>
            <CountriesProvider countries={countries}>
              <NavBar />
              {children}
              <Footer />
            </CountriesProvider>
          </ReactQueryProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
